{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/gx/anaconda3/envs/tf1.14/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint8 = np.dtype([(\"qint8\", np.int8, 1)])\n",
      "/home/gx/anaconda3/envs/tf1.14/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint8 = np.dtype([(\"quint8\", np.uint8, 1)])\n",
      "/home/gx/anaconda3/envs/tf1.14/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint16 = np.dtype([(\"qint16\", np.int16, 1)])\n",
      "/home/gx/anaconda3/envs/tf1.14/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint16 = np.dtype([(\"quint16\", np.uint16, 1)])\n",
      "/home/gx/anaconda3/envs/tf1.14/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint32 = np.dtype([(\"qint32\", np.int32, 1)])\n",
      "/home/gx/anaconda3/envs/tf1.14/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  np_resource = np.dtype([(\"resource\", np.ubyte, 1)])\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:\n",
      "The TensorFlow contrib module will not be included in TensorFlow 2.0.\n",
      "For more information, please see:\n",
      "  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md\n",
      "  * https://github.com/tensorflow/addons\n",
      "  * https://github.com/tensorflow/io (for I/O related ops)\n",
      "If you depend on functionality not listed there, please file an issue.\n",
      "\n",
      "WARNING:tensorflow:From /home/gx/anaconda3/envs/tf1.14/lib/python3.6/site-packages/neuralgym/ops/layers.py:142: The name tf.image.resize_bilinear is deprecated. Please use tf.compat.v1.image.resize_bilinear instead.\n",
      "\n",
      "WARNING:tensorflow:From /home/gx/anaconda3/envs/tf1.14/lib/python3.6/site-packages/neuralgym/callbacks/npz_model_loader.py:31: The name tf.get_variable_scope is deprecated. Please use tf.compat.v1.get_variable_scope instead.\n",
      "\n",
      "WARNING:tensorflow:From /home/gx/anaconda3/envs/tf1.14/lib/python3.6/site-packages/neuralgym/ops/gan_ops.py:138: The name tf.layers.Conv2D is deprecated. Please use tf.compat.v1.layers.Conv2D instead.\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "os.environ[\"TF_CPP_MIN_LOG_LEVEL\"]='2'\n",
    "import cv2\n",
    "import numpy as np\n",
    "import tensorflow as tf\n",
    "if(tf.__version__=='2.1.1'):\n",
    "    import tensorflow.compat.v1 as tf\n",
    "    tf.disable_v2_behavior()\n",
    "\n",
    "import neuralgym as ng\n",
    "\n",
    "from inpaint_model import InpaintCAModel\n",
    "from tensorflow.python.framework import graph_util"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "path = '/home/gx/myproj/generative_inpainting-master/'\n",
    "myimage =  'examples/places2/case1_raw.png'\n",
    "mymask = 'examples/places2/case1_mask.png'\n",
    "mycheckpoint_dir = path + '/model_logs/release_place2_256'\n",
    "myout = 'outputlinux1ss.png'\n",
    "output_graph = 'frozen_model_1_14.pb'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "def image_input_pros(myimage, mymask):\n",
    "    image = cv2.imread(myimage)\n",
    "    mask = cv2.imread(mymask)\n",
    "    assert image.shape == mask.shape\n",
    "    h, w, _ = image.shape\n",
    "    grid = 8\n",
    "    image = image[:h//grid*grid, :w//grid*grid, :]\n",
    "    mask = mask[:h//grid*grid, :w//grid*grid, :]\n",
    "    # print('Shape of image: {}'.format(image.shape))\n",
    "    image = np.expand_dims(image, 0)\n",
    "    mask = np.expand_dims(mask, 0)\n",
    "    input_image = np.concatenate([image, mask], axis=2)\n",
    "    # input_image = tf.constant(input_image, dtype=tf.float32)\n",
    "    return input_image   # must be a np data   cannot feed a tf.tensor\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "def save_imagedata(npa,dim):\n",
    "    import os\n",
    "    try:\n",
    "        os.remove('debug.txt')\n",
    "    except:\n",
    "        pass\n",
    "    with open('debug.txt','w+') as f:\n",
    "        temp = npa[0][:,:,dim].flatten()\n",
    "\n",
    "        print(npa.shape)\n",
    "        index = 1\n",
    "        sum = 0\n",
    "        for i in temp.tolist():\n",
    "            f.write(str(i)[0:8])\n",
    "            sum +=1\n",
    "            f.write(',')\n",
    "            if index%680==0:\n",
    "                f.write('\\n')\n",
    "            index +=1\n",
    "        print(sum)\n",
    "    res = (npa+1) * 127.5\n",
    "    import time\n",
    "    cv2.imwrite('output_debug_'+str(int(time.time()))+'.png', res[0][:, :, 0:3])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "# def save_imagedata(npa,filename):\n",
    "#     import os\n",
    "#     try:\n",
    "#         os.remove(filename)\n",
    "#     except:\n",
    "#         pass\n",
    "#     with open(filename,'w+') as f:\n",
    "#         temp = npa.flatten()\n",
    "\n",
    "#         print(npa.shape)\n",
    "#         index = 1\n",
    "#         sum = 0\n",
    "#         for i in temp.tolist():\n",
    "#             f.write(str(i)[0:8])\n",
    "#             f.write('\\n')\n",
    "#             sum +=1\n",
    "# #             f.write(',')\n",
    "# #             if index%680==0:\n",
    "# #                 f.write('\\n')\n",
    "# #             index +=1\n",
    "#         print(sum)\n",
    "# #     res = (npa+1) * 127.5\n",
    "# #     import time\n",
    "# #     cv2.imwrite('output_debug_'+str(int(time.time()))+'.png', res[0][:, :, 0:3])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "# save_imagedata(result2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "---------------------------------- APP CONFIG ----------------------------------\n",
      "num_gpus_per_job: 1\n",
      "num_cpus_per_job: 4\n",
      "num_hosts_per_job: 1\n",
      "memory_per_job: 32\n",
      "gpu_type: nvidia-tesla-p100\n",
      "name: places2_gated_conv_v100\n",
      "model_restore: model_logs/release_places2_256\n",
      "dataset: celebahq\n",
      "random_crop: False\n",
      "val: False\n",
      "log_dir: logs/full_model_celeba_hq_256\n",
      "gan: sngan\n",
      "gan_loss_alpha: 1\n",
      "gan_with_mask: True\n",
      "discounted_mask: True\n",
      "random_seed: False\n",
      "padding: SAME\n",
      "train_spe: 4000\n",
      "max_iters: 100000000\n",
      "viz_max_out: 10\n",
      "val_psteps: 2000\n",
      "data_flist: \n",
      "  celebahq: ['data/celeba_hq/train_shuffled.flist', 'data/celeba_hq/validation_static_view.flist']\n",
      "  celeba: ['data/celeba/train_shuffled.flist', 'data/celeba/validation_static_view.flist']\n",
      "  places2: ['data/places2/train_shuffled.flist', 'data/places2/validation_static_view.flist']\n",
      "  imagenet: ['data/imagenet/train_shuffled.flist', 'data/imagenet/validation_static_view.flist']\n",
      "static_view_size: 30\n",
      "img_shapes: [256, 256, 3]\n",
      "height: 128\n",
      "width: 128\n",
      "max_delta_height: 32\n",
      "max_delta_width: 32\n",
      "batch_size: 16\n",
      "vertical_margin: 0\n",
      "horizontal_margin: 0\n",
      "ae_loss: True\n",
      "l1_loss: True\n",
      "l1_loss_alpha: 1.0\n",
      "guided: False\n",
      "edge_threshold: 0.6\n",
      "--------------------------------------------------------------------------------\n",
      "------------------\n",
      "(1, 512, 680, 1)\n",
      "(1, 512, 680, 1)\n",
      "(1, 512, 680, 1)\n",
      "WARNING:tensorflow:From /home/gx/myproj/generative_inpainting-master/inpaint_ops.py:48: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use `tf.keras.layers.Conv2D` instead.\n",
      "WARNING:tensorflow:From /home/gx/anaconda3/envs/tf1.14/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Call initializer instance with the dtype argument instead of passing it to the constructor\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4036956780>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4036956780>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4036956780>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4036956780>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4036956780>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4036956780>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4036956780>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4036956780>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f407c658ef0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f407c658ef0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f407c658ef0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f407c658ef0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dfc3c88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dfc3c88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dfc3c88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dfc3c88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dfc3c88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dfc3c88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dfc3c88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dfc3c88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dfc3c88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dfc3c88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dfc3c88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dfc3c88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dfa0a20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dfa0a20>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dfa0a20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dfa0a20>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f40390f4278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f40390f4278>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f40390f4278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f40390f4278>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f40390f6278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f40390f6278>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f40390f6278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f40390f6278>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401df510b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401df510b8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401df510b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401df510b8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f40390f6278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f40390f6278>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f40390f6278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f40390f6278>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dddfc50>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dddfc50>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dddfc50>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dddfc50>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dc998d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dc998d0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dc998d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dc998d0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f40390f6278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f40390f6278>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f40390f6278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f40390f6278>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dca0898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dca0898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dca0898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dca0898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f40390f6278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f40390f6278>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f40390f6278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f40390f6278>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dd7d0f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dd7d0f0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dd7d0f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dd7d0f0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dc62e10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dc62e10>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dc62e10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dc62e10>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dba9a90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dba9a90>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dba9a90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dba9a90>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dd09080>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dd09080>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dd09080>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dd09080>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dba9a90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dba9a90>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dba9a90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dba9a90>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dd09080>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dd09080>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dd09080>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dd09080>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dad5550>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dad5550>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dad5550>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dad5550>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401da8ae10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401da8ae10>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401da8ae10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401da8ae10>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dad5550>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dad5550>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dad5550>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401dad5550>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401db27fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401db27fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401db27fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401db27fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401db0b320>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401db0b320>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401db0b320>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401db0b320>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401da76940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401da76940>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401da76940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401da76940>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401db0b320>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401db0b320>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401db0b320>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401db0b320>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401da76940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401da76940>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401da76940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401da76940>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401db0b320>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401db0b320>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401db0b320>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401db0b320>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401da76940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401da76940>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401da76940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401da76940>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401db0b320>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401db0b320>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401db0b320>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401db0b320>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d879470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d879470>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d879470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d879470>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d7b90f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d7b90f0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d7b90f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d7b90f0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "#########################\n",
      "(1, 128, 170, 96)\n",
      "(1, 128, 170, 96)\n",
      "(1, 128, 170, 192)\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d721588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d721588>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d721588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d721588>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d721588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d721588>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d721588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d721588>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401de5d7f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401de5d7f0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401de5d7f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401de5d7f0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d721588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d721588>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d721588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d721588>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d7f8da0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d7f8da0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d7f8da0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d7f8da0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d6ebfd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d6ebfd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d6ebfd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d6ebfd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d721588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d721588>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d721588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f401d721588>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "Model loaded.\n",
      "(1, 512, 1360, 3)\n",
      "(1, 512, 680, 3)\n",
      "(1, 512, 680, 3)\n",
      "348160\n"
     ]
    }
   ],
   "source": [
    "with tf.Graph().as_default():\n",
    "    input_image_holder = tf.placeholder(tf.float32, [1,512,1360,3], name='input_image_holder')\n",
    "    # output = tf.extract_image_patches(input_image_holder,sizes=[1, 4, 4, 1], strides=[1, 7, 7, 1], rates=[1, 1, 1, 1], padding='SAME')\n",
    "    with tf.Session(config=tf.ConfigProto()) as sess:\n",
    "        FLAGS = ng.Config('inpaint.yml')\n",
    "        temp = InpaintCAModel()\n",
    "        output,debug_tensor = temp.build_server_graph(FLAGS, input_image_holder) # build inpaint model\n",
    "        output = (output + 1.) * 127.5\n",
    "        output = tf.reverse(output, [3])\n",
    "        other_output = output\n",
    "        output = tf.saturate_cast(output, tf.uint8)  # change output into 0-255 uint8\n",
    "        # tf.identity(output, name=\"output_inage_holder\")\n",
    "        # load pretrained model\n",
    "        vars_list = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES)\n",
    "        assign_ops = []\n",
    "        index = 1\n",
    "        for var in vars_list:\n",
    "            vname = var.name\n",
    "            var_value = tf.contrib.framework.load_variable(mycheckpoint_dir, vname)\t\n",
    "            # print(vname+': '+str(var_value.shape))\n",
    "            assign_ops.append(tf.assign(var, var_value))\n",
    "            # print(assign_ops[0])\n",
    "            index = index + 1\n",
    "        sess.run(assign_ops)\n",
    "        # print(len(assign_ops))\n",
    "        print('Model loaded.')\n",
    "\n",
    "        input_dict = {input_image_holder:image_input_pros(myimage, mymask)}\n",
    "        print(image_input_pros(myimage, mymask).shape)\n",
    "\n",
    "        from datetime import datetime\n",
    "        a = datetime.now()\n",
    "\n",
    "        # result = sess.run(output, feed_dict=input_dict)\n",
    "#         debug_tensor = tf.get_default_graph().get_tensor_by_name('inpaint_net/allconv17/kernel/read:0')\n",
    "        result2 = sess.run(debug_tensor, feed_dict=input_dict)\n",
    "        print(result2.shape)\n",
    "        save_imagedata(result2,0)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "# cv2.imwrite('output_debug_'+str(int(time.time()))+'.png', result2[0][:, :, 0:3])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "# save_imagedata(result2,0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "# save_imagedata(result3,'debug_filter.txt')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "def myelu(mylist,alpha):\n",
    "    res = []\n",
    "#     alpha = 0.1\n",
    "    if alpha == -233:\n",
    "        return mylist\n",
    "    for i in mylist:\n",
    "        if i<0:\n",
    "            res.append(alpha*(exp(i)-1))\n",
    "        else:\n",
    "            res.append(i)\n",
    "    return res"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "lineIndex = 5\n",
    "\n",
    "p = result2[0][lineIndex,:,0].flatten().tolist()\n",
    "with open('/home/gx/myproj/tensorflow2ncnn/build/examples/data.txt','r') as f:\n",
    "    i = 0\n",
    "    for line in f:\n",
    "        if i == lineIndex:\n",
    "#             print(line[:-2])\n",
    "            exec('c=['+line[:-2]+']')\n",
    "        i += 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(1, 512, 680, 3)"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "result2.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Populating the interactive namespace from numpy and matplotlib\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/gx/anaconda3/envs/tf1.14/lib/python3.6/site-packages/IPython/core/magics/pylab.py:160: UserWarning: pylab import has clobbered these variables: ['datetime', 'f', 'var']\n",
      "`%matplotlib` prevents importing * from pylab and numpy\n",
      "  \"\\n`%matplotlib` prevents importing * from pylab and numpy\"\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAX4AAAD4CAYAAADrRI2NAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAgAElEQVR4nO3deZhcdZXw8e+pvXpJd0I6EJJAgkQgLAK27EtGBg2MwuC4BPVVZ1TcYGYU33lxeSKGwe31dWZUYERFEWdgGBxnosZBBogsRkiHQCAJgRBCNkg6JJ1Od+1V5/3j3uqu9Hqrq7q2Pp/n6adv3a1O9VN96le/+7vnJ6qKMcaYqcNX7QCMMcZUliV+Y4yZYizxG2PMFGOJ3xhjphhL/MYYM8UEqh3AUDNnztT58+dXOwxjjKkra9eu3aeqHV72rbnEP3/+fLq6uqodhjHG1BURecXrvtbVY4wxU4wlfmOMmWIs8RtjzBRjid8YY6YYS/zGGDPFWOI3xpgpxhK/McZMMTU3jt80rke++AFyO3ccvjIS4YybfkTbkcfw8hP388qtX4OhpcKjUTq/fictM44il83w6Offi76+b8znar7oT3nLx5aV+RUY0xik1urxd3Z2qt3A1Xj2vrSeWce/CYCcuy7/dfMP37iW8/7P9/j9O0/j4l8/O7C9cJ8nvncDZ1/7dbY8toLjL7zysPMM5QO2dQSZvzdV3hdhTA0TkbWq2ullX+vqMRXRv+9VAB7/2qfwqeJT5dVNawDIHNwPgP9QPztmBAa2+1R5petBANI9rwOQ2L8XgDU//Oph+xX+PHrJQkLp0T4WjDGW+E1FJN3kHpjWPrCuafosAHJ9fc62eIJExH/YcQP7HDoEQOrgAQBCbTNGfS4NBghmLPEbMxpL/KYikgedFnuwIPE3u0mdPiepB+JJkuHDLztF22cCkOvrBSDd6yb+adNHfS4NBQlmyhO3MY3IEr+piJTb4i9sqQdCERIBoL/f2RZPkYqGDjuuqc1J/Pl9MocOAhBxPxBGosEggVxtXbsyppZY4jcVkU/YQ1vq/SFB+mMAhBNp0tHwYdt9/gD9QcDtDsrmE3/bEaM/WShEKFumwI1pQJb4TUXkE3a0/fBy4fGwD38sDkA4mSXTFB52bCws+Nx98tcD8n3/I3ITv+asn9+YkVjiNxWRPeT00Q9N/IlwAH8s4WxLZMk2RYcdGwv7BxJ//npA81iJPxgEIJ2MlRq2MQ3JEr+pCHUTdtP0IYk/GiDoJv6mZI5cU9OwY5PhAAF3H/r6SASc6wOjCjnXCVLxvjJEbkzj8ZT4RWSJiGwWkS0icsMI248VkQdFZL2IrBKRue7600VktYhscLe9r9wvwNSHN9z7PwBEWw8fhpmKhjjm5QM8eslCmlNAS/OwY5PRAMdu3sOjlyxk3iNP0x+SMZ9LQk53UTreX57gjWkw4yZ+EfEDtwCXAYuAq0Vk0ZDdvg38TFVPA5YDX3fXx4APqerJwBLgH0WkHTOlZNMp5u3PkPKD+A5/y/VefA6poLBg3cvsPCJAy5+8fdjxr1/0FrJ+Z59wMsums48b8/nyiT+TjJfvRRjTQLzU6jkL2KKqWwFE5B7gSmBjwT6LgM+5yw8D/wmgqi/kd1DV3SKyF+gAekoP3dSL2MF9tAJ/+OSfsXjItsW3roRbBx8fM8Lxi+94CO4YfDx3nOeTsLX4jRmLl66eOUBhZa2d7rpCzwDvcpevAlpF5LDxdiJyFhACXhr6BCJyjYh0iUhXd3e319hNnYgdcMos+FqnVeT5JOz0/6cTlviNGUm5Lu5+HrhYRNYBFwO7gIGR1CIyG7gL+EtVHTbGTlVvV9VOVe3s6OgYutnUuYR7166vpTKJ3+de3M0kbFSPMSPx0tWzC5hX8Hiuu26Aqu7GbfGLSAvwF6ra4z6eBvwG+JKq/rEcQZv6kuhxSigHprVV5Pl8bovfEr8xI/PS4l8DLBSRBSISApYCKwp3EJGZIpI/1xdwe2Td/X+Jc+H3vvKFbepJvkBbsLUy1/XziT+bSlTk+YypN+MmflXNANcC9wObgHtVdYOILBeRK9zdFgObReQF4EjgZnf9e4GLgI+IyNPuz+nlfhGmtqV6h9fpmUz+sHMTWDZho3qMGYmnGbhUdSWwcsi6ZQXL9wHDWvSq+nPg5yXGaOpc+qAziCvcPkZ9nTLyR9zEb8M5jRmR3blrJl22z6nTE55mLX5jaoElfjOmVR+8gEfeflJJBc/ydXrGLKxWRn63nMNxn/4Sh/btLvv5V/3VW1l7yhGs/8VtZT+3qT+H9u3mj2cdzSNf/lC1Q/HMEr8Z0+J/eZyLfvc8vd07J3yOwTo9lUn8886+lH3NwvS4su3RX5X9/Kfcu4o3b9jP/nt/WvZzm/qz7dFfcc6aV7ng5ruqHYpnlvjNqApb+fGD+yZ+IreUcrRCXT2tM49m9523AJByZ+wqp0jameRFYtaVZAbfY/WUTOspVlNhyVjvwHL8QAl3VPf10xdyJlWplPyF5HSZE38um6El5Sz7++0+AVP+91glWOI3o4oVJPv8WPyJ8MVixEKVfavlZ+jK9B4s63ljBd988vMImKktfw2rnljiN6PK19iBwcnSJ8IfixMPV/atFnXr/ucnaS+XeM9g4g/Ek2U9t6lP+dnl6oklfjOqRO9gsk+V0OL3x5MkIpXr5gGIupO058rcGiv8MAzFU2U9t6lPhe+xXDZTxUi8s8RvRpXsGUz8mRJaNcFYklSFE3+Tm/jzF5bLJVHQ4g8n0mU9t6lT/YNVYOO9E28gVZIlfjOqwlZ+KV9nQ/EUqWioHCF55g+GiAU57J+yHPIjOA5EhXCiPlp3ZpIVNC5iPfVRVt4SvxlVundwvpxSLmCFExnS0XA5QipKf0jwlXnkTf7DcH9bkGgyO87eZirwFQzrjddJ4hdVrXYMh+ns7NSurq5qhzHlvbppDbMXnTXw+PUm4VDzxLpr5rye5okLF3DBqq3lCs+T7TODtPdl2HTKUZzd9WrJ5+ve+hwdbzgVgHUntnPG8z08/vVPM/P7dxBOOR8C6aAPufvfOP6iK4kd3MeWzuOYdtBG/4xm+zVLuejvfzZs/d6X1vP6W88hGi/+W1VfS4hjnnieaR3D52pbde07mH/v7yYU62hm9KaZ5l7n3zndTyZweHs6J0LPt/+eM//X/y7r8w4lImtVtdPLvpXteDV1Y+djK5kNrD++lf3nnk5w2/YJn2sX0Prpz5YtNq9e+dT7if/kXs5e+xrZdAp/sLTupp2r76cD2DQvSub6z8LHv0Lrj+/ihF0Jnjx9FhrwcXbXazz2yG84/qIreW3jk5y25RDrj2/l0OzK3LxWT0558hV2P7RqxG271zzM6dvjPLVoOvEjvE/g07LnAG96oZcXNjzBtMXDE3/rqtW0xDJsPnOkST4nZheQXnQivq3b8CeGf8if/+grrHrwNzDJib8YlvjNiPLdPE0/vovTLrqyytFMzIU33cmq7j2c8IP7SSdjJSf+fHlpbr+dN1385/Dxrwy05mf/5N+JTJsBbzh1oFssfyE4/rnrOP9TN494zqnshTlRfJmRW/T5yqqB5Tdz/l98yvM5n7jtS/Dpr41aoM+fybJjXhvnP7Kt6HgnKhaSsg8yKJX18ZsR5S/mRipUSnnShJxrC6l46f942V4noYfbZhCKtpDyO1/zAaLtHQO1iPK1iVIHnQvBoQqVqqg3mYAPf3rkxJ9LOh+ogUhTUefMV2YdbfY1fzpLNugv6pyl6g/JYdcBaoElfjOi/NjkaHt9z4EsYaeVn46XPronP6Q1/zfpD8lA327T9I7BWkRu6y5/K3+lJqCpN9mgD1965Avk+RZ/fm4Fr8YryR3IZMkFKpv44xF/fSZ+EVkiIptFZIuI3DDC9mNF5EERWS8iq0RkbsG2D4vIi+7Ph8sZvJk8AxU16z3xuy3+TBkmZRn4MHTvEYi5dyPngGjrDHz+AH0hoM/5kEkfquw8BPUmG/Djz4yc+Cfc4nc/KHLpke+qDmRy5IKV7eFOhv0Eaqy8x7iJX0T8wC3AZcAi4GoRWTRkt2/jzKt7GrAc+Lp77AzgK8DZwFnAV0RkevnCN5Omv5+sQKSlMvPkThYJlq/FT7/Tkm9yy0Ekwk7LsT8E4nP+leIhwRdzuhmy7nWSSPvM0p+7AWWDoyd+TTl3RQfC5W3x+zNa8RZ/IhIkWGPlPby0+M8CtqjqVlVNAfcAQ6/2LQIecpcfLtj+duABVd2vqgeAB4AlpYdtJpu4FTXzCa1e5SdeH63Ptyh9fST9EIq2AJB070aOFdQhioX9+N2v9bkKz0NQb7KBAP70yBP8TLTFn98/f/yw7dkcuWCwqHOWKhUNEayxu7y9/FfPAXYUPN7priv0DPAud/kqoFVEjvB4LCJyjYh0iUhXd3d93ADR6Hz9sYoXVpsM5Uz80h9zRmi4UhEngcQjgy3IRCQw8LV+cAKa+u4umyy5oJ9AZuTErymnhRyMNhd1zvzsa9lREn8wk0Mr3NWTiYYIx+sv8XvxeeBiEVkHXIwztNXzbY2qeruqdqpqZ0eH/ZPUAn88QTxc2a/Ek6Gcid8Xix/Wuk+5dyMnC/5OqUiAYMz9Wt/XR8YH4Sbv49CnklwggD87SuJPuok/Ulziz7f48x8cw7ZnFA1VtsWfaYoQqbHyHl4S/y5gXsHjue66Aaq6W1XfpapnAF9y1/V4OdbUnlWfexfnPb6dRLT+b/MYSPzJ0hL/77/4AS58aAuJgtZ9ptk5d6KgDlGyKcyZGw+QDAgX3v0H+kJS991lkyUXCpS9xT9eV08oq2iFu3qyzU0c+3qG/c0+Xn6yvHcNT5SXd+QaYKGILBCRELAUWFG4g4jMFJH8ub4A3OEu3w+8TUSmuxd13+auMzUs8NTTAMSWL6tyJKXzu4k/N0oL0CvpWgvA/pu+NLBuxrJvsGrpOejy5QPrwl+9mVVLz2H1e87h0fedw8abrivpeRuZBgIEs6OUjHEv7gbDxfXx5z8oRmvxB7NUvKtnzpe+yaOXLGRGTOle91hFn3s04/4FVDUjItfiJGw/cIeqbhCR5UCXqq4AFgNfFxEFHgE+4x67X0RuwvnwAFiuqvVRt3QKC8QSbJ4T4c0fHjZyt+6MN8rDq0AszsuzgrzlY4Mfhie+7WpOfNvVh+136lWfgKs+UdJzTRUaChIcpcVP2ukTDxZ5cTffNZTvKhq2PQuEKlsp9g3nvwO+Cjz4TjIFhQ+rydNHn6quBFYOWbesYPk+4L5Rjr2DwW8Apg5Uo37+ZMmP686WOI4/EEuQCDfG36RWaDBIcLSu71SKtA+CRc7TPFaLP5fNEMxR8cQPg1OBZss8FehEWeejGSaUqHz9/Mky0OIvMfEHEylS0cr2DTc6DQYI5Ebv6klNYGzBwDeE9PBRNOn8Bf4qJP78kN78EN9qs8RvhgnHq1M/fzIM9PGPUDWxGKF4mlSkMT4Ma0YoRGiUsX+SSpOZSOLPXxNIDZ8Wc6BeU4Uv7gI0zzgSGBziW22W+M0wkWSGTFOk2mGUxeDwvtLmx40k0mSaGuPDsGa4iV9zw/v5JZ0m5ZcRDhqbPxgi42PExJ+/eztfxqOSQtEW0j7KPiPcRFniN8NEk1ly0cZI/PmLfaMN7/MqnMySbZC/Sc1wu1zSIwy1lVSaTKD4xA84XUQjJf6Em/jD1fkA7w8JYonf1KqmpJJrLm40Ra0aGNdd4nDOpmSObIP8TWpGPvGPcHOdZLKkAxNLT2k/yAjlnvOF+qrR4geIRXz4+mujSqcNU2gQqXgfPa9tG3h8xNw3Fj3xSDoRY//OFzkyDTQXd+NMrRpo8ZcwZzDAjJiiTcUVDDNjyyfgPS88Rcusw2fLCvbHyPgnlvhTfsHXe4i9Lz932PoDL29kDoM39VVaIuQn1OPEFQw3Mf3o46oSB1jibxibT5nNqVsHJxv5w3nzOO/x4qZLfO6MOZzxvDvOuL0xiqhGpjmvY/F3/4vuH/vo6Btl3PgYHlv+MS4AmGalF8rJ19IKwHHnXDZs2yycKS4nIhH2c+FDW+C4U4edE8DvPm+l9beEOHvtawNxPXHrFzm7SjOzWeJvEEe/1s/TJ7TRe+USZv/8P2nf+XrR5zjytUM8+4ZWet53JWdc9/eTEGXltcw4ipdnBVmwN01H/yhDB8eReXEzAKctu7WcoU15p//113hUddS7bDv+5B0TOm/PD7/Hy0+sGnGbRJvo/Eh1bkwM/eBHPPLAL9F4nIu/t4L48xuqEgdY4m8YTSml57Q3svib9/CHR4/hqJf2FH2OaDLH/pMXcPHNd01ChNWz/ZxFLFjxzMRP0B/jUAhmzFtYvqAMrTOP5sKb7iz7eU991yfhXZ8s+3lLdcKfvo8T/vR9zjWN7zUPzO9QDXZxtwFk0ymiGaDFqROfbYoQSXkujjqgOaVoU+NdwCy1GqOvP3ZYVU5jShGMNJH0U9UJ2O3d3AD6e/Y6C+4F2VxzlKZEcX3ZqXifczON++HRUEq8U9Mfjx9Wc9+YUvWHBekvw+RAE2SJvwHEDjiJ39fqXHzU5maaU8X1Z8cOOBPgSJUufE2qEu/UDMSSh9XcN6ZUsbCvqhOwW+JvAIke50Kuv7XNWdHcTDBXcIu6BwMfHo2Y+Ets8QfjSZIRq9NjyseZgN0SvylBomcfAAE38edb7f37vV/gTfS6Hx7T2socXQ0oMfGH4o1TtM7UhkQkSCBeWhmRUljibwDJg07SDrY5Y9bzrfZ8K96LgQ+PlsZL/KXeqRlOZMg0SNE6UxtSkSCheGl3k5fChnM2gJ7VDwMQapsBDLbatz9wHwd3vOjpHPsec6aEy394NJKJ1mbRXI6tq1fS0p9mT4MUrTO1IR0NccTuHrY9+QDzz7q04s/vKfGLyBLgn3Bm4PqRqn5jyPZjgDuBdnefG1R1pYgEgR8BZ7rP9TNV/XoZ45/yXvz9L7n4H/4DgNajFwAQOcqZ5vjcz32n6PM1H31s+YKrEYUt/mw65bmUxcaVd3LyO/8KgM0zGu8D0VRPckYbb1i3F85+G9ue+F3Fk/+4iV9E/MAtwKXATmCNiKxQ1Y0Fu30ZuFdVbxORRTizdc0H3gOEVfVUEWkCNorI3aq6rcyvY8rq3ebcVbrqU5exuPMSAE5//2dZ5/OR7itutp/wjFmcdtFVZY+x2goTfyreRzQ4w9Nxfa8435Z+//l3c8bn/9+kxGamppN/8htW3fQZFv/wAQ6+shlqLfEDZwFbVHUrgIjcA1wJFCZ+BfKFTNqA3QXrm0UkAESBFFBatSxzmHTvAQBmv+vDA+t8/gBnfOD6aoVUc3zhIYl/mrfEn58f9Zh3f4y2I4+ZlNjM1DRj3kJmvuO98MMHSB2s/DTkXi7uzgF2FDze6a4rdCPwQRHZidPav85dfx/QD7wKbAe+bZOtl1fWrToZ9pjMpiIJDHbt5Cfj8CLb5/xto9M7yh6TMWF3Ht7MocrPw1uuUT1XAz9V1bnA5cBdIuLD+baQBY4GFgDXi8iwWqQico2IdIlIV3d3d5lCmhqy7pvGktPoxDc4oUcm5X3sdO6QM01etG1m2WMyZmAC9hpN/LuAeQWP57rrCn0UuBdAVVcDEWAm8H7gv1U1rap7gceBzqFPoKq3q2qnqnZ2dFgCK0Z+8ub8ZM5mBFKQ+EeY9GNUbhGtZvvbmkkQbXdyXbbEuSImwkviXwMsFJEFIhIClgIrhuyzHbgEQEROwkn83e76t7rrm4FzgOfLE7oBBgo9NVmrdHQ6WL6imK4e+vpIBCAQsqGcpvya3G/p1ZiAfdzEr6oZ4FrgfmATzuidDSKyXESucHe7Hvi4iDwD3A18RFUVZzRQi4hswPkA+Ymqrp+MFzJl9fURC1L0bFtTVTEtfumP0R+a2Lyvxown2jqDHFSlSqencfyquhLnom3humUFyxuB80c4rg9nSKeZJL5YnFhIaLxiypOjmMTvj8WJWzlmM0nE5+NQGKhClU67c7eObfztz2jduou4VY4cW0Ef/55f3sXBzd4mZWnbvodE2P5FzOSJh3y0vriNP3737wAIzzyKM97/uUl/XlGd2HR0k6Wzs1O7urqqHUbNSydi5FqaCWdh/fGtnPai3R4xmq2rV3LceX82oWPXnjyDNz9X/DSWxnix8dhmFm0fbPE/t6CZU7ZOrOtHRNaq6rDBMyOx5kyd6nv9VaZnYdV7z+LM7/+i2uHUtOPOvZyeXVvp3fPKQDE6r9546nmTFJUxMOeJjbywac3A49bWypQGscRfp+I9+5gO+E84iWkdc6sdTs1rP3oB7W4tI2NqRdtRx9J2VOXrY9mVqzoV73FudPO3ThtnT2OMOZwl/jqV7HUqXwSmtVc5EmNMvbHEX6fyhZ2CrZb4jTHFscRfp/KJP1/oyRhjvLLEX6fyFf3C7Zb4jTHFscRfp7K9TuKPWIvfGFMkS/x1yqpyGmMmyhJ/ncpX9GuecWSVIzHG1BtL/PWqr4+0D0LRlmpHYoypM5b465SVDDbGTJQl/jrl648RD1viN8YUzxJ/nfLHE8StZLAxZgIs8depQCxJImKJ3xhTPE+JX0SWiMhmEdkiIjeMsP0YEXlYRNaJyHoRubxg22kislpENojIsyJiE5iWQSieJBUNVjsMY0wdGjfxi4gfZ+7cy4BFwNUismjIbl/GmYv3DJzJ2G91jw0APwc+qaonA4uBdNmin8JCiTTpqM2za4wpnpcW/1nAFlXdqqop4B7gyiH7KJCvD9wG7HaX3wasV9VnAFT1dVXNlh62CScyZCLhaodhjKlDXhL/HGBHweOd7rpCNwIfFJGdOJOyX+eufyOgInK/iDwlIn830hOIyDUi0iUiXd3d3UW9gKkqmsySaY5WOwxjTB0q18Xdq4Gfqupc4HLgLhHx4czwdQHwAff3VSJyydCDVfV2Ve1U1c6Ojo4yhdTYoskcOUv8xpgJ8JL4dwHzCh7PddcV+ihwL4CqrgYiwEycbwePqOo+VY3hfBs4s9SgDTSnFG1qqnYYxpg65CXxrwEWisgCEQnhXLxdMWSf7cAlACJyEk7i7wbuB04VkSb3Qu/FwMZyBT9VpeJ9hLJAi5VrMMYUb9yB4KqaEZFrcZK4H7hDVTeIyHKgS1VXANcDPxSRz+Jc6P2IqipwQES+g/PhocBKVf3NZL2YqSJ2oJsQIC2t1Q7FGFOHPN0BpKorcbppCtctK1jeCJw/yrE/xxnSacokdmAv7YDPEr8xZgLszt06lOh9HQD/tLYqR2KMqUeW+OtQomcfAIEWS/zGmOJZ4q9DqYMHAAi2Ta9yJMaYemSJvw6le53EH7b5do0xE2DlHStk7Z3fIHXb98tyrta9PQCErMVvjJkAS/wVkvzBrby5axfbZ5Wnvs66E9s54dTzynIuY8zUYom/QoLxBFvnRDnplVi1QzHGTHHWx18hwXiKpJVRNsbUAEv8FRKKW/18Y0xtsMRfIeGk1c83xtQGS/wVYvXzjTG1whJ/hVj9fGNMrbDEXyFWP98YUyss8VeA1c83xtQSS/xFWHX1uaw+Zy7ZdMrzMZv+++dsPmU2ANJsid8YU312A1cRFt/zRwD27XqJmfNP8nTMnl/dzeKtfTx5+izmvuejkxmeMcZ44qnFLyJLRGSziGwRkRtG2H6MiDwsIutEZL2IXD7C9j4R+Xy5Aq+mdKLf+859fQB0du3iDee/Y5IiMsYY78ZN/CLiB24BLgMWAVeLyKIhu30ZuFdVz8CZk/fWIdu/A/y29HCrR3O5geVsKuH9wL5++oPg89uXK2NMbfDS4j8L2KKqW1U1BdwDXDlkHwWmucttwO78BhH5c+BlYEPp4VZP/ND+geV03HuL3xeLEQvLZIRkjDET4iXxzwF2FDze6a4rdCPwQRHZiTM373UAItIC/B/gq2M9gYhcIyJdItLV3d3tMfTK6t+/Z2A5k/BeaM0fixMP+ycjJGOMmZByjeq5Gvipqs4FLgfuEhEfzgfCP6hq31gHq+rtqtqpqp0dHR1lCqm8EgdfH1guKvHHkyTC1s1jjKkdXjLSLmBeweO57rpCHwWWAKjqahGJADOBs4F3i8i3gHYgJyIJVS3PjCQVFO8Z/CaSTcY9HxeMJUlGLPEbY2qHl4y0BlgoIgtwEv5S4P1D9tkOXAL8VEROAiJAt6pemN9BRG4E+uox6QMkewZb/NmE98QfiqdIWVVOY0wNGberR1UzwLXA/cAmnNE7G0RkuYhc4e52PfBxEXkGuBv4iKrqZAVdDelDPQPL2aT3UT3hRIZ0k1XlNMbUDk99EKq6EueibeG6ZQXLG4HzxznHjROIr3Z84xsDi8V09USSGbJRS/zGmNphJRs8ajo02MrPFdHijyazZJusKqcxpnZY4vconMjwwtERoLjE35RUcs1WldMYUzss8XsUTWaJtTpdNl4Tfy6boTkNNDdPYmTGGFMcS/weRZM5EtOclrvXxB87uM9ZsHLMxpgaYonfA83laElBepqTwNVjWebYgb0ASEvrpMVmjDHFssTvQTLWi18h2+6UI9JU0tNx8R6nxe9vnTbOnsYYUzmW+D0YqNMzfToAmvTW4k+4iT8wrX1S4jLGmImwxO9BvuUuM45wVnhs8efv9g20tk1KXMYYMxFWRMaDfMs9OHOWsyIeJ+2hUFuq1ynlHJo2Y9JiM8aYYlni92DPl/+G44HQzCNJ+WHxzx6Bn40/RLPT/R1us8RvjKkdlvg9CB1yWvenvOczrD3YQ3LD0+Mec9T9j3PiDqe0Q6R95qTGZ4wxxbDE70EwnuLpE9o4vaWdc//2/3o65pHLFnHijk0ARKfX5hwDxpipyS7uehCKp0kVWWitsExDtM1a/MaY2mGJ34NIIkOm2AqbBWUamizxG2NqiCV+D6LJDNmmSHEHFZRp8AdtIhZjTO2wxO9BNKnkmosrrWxlGowxtcpT4heRJSKyWUS2iMgNI2w/RkQeFpF1IrJeRC53118qImtF5Fn391vL/QIqoTmlaJEVNq1MgzGmVo07qkdE/MAtwKXATmCNiKxwZ93K+zLOlIy3icginNm65gP7gHeq6m4ROQVn+sY5ZX4NkyoV7yOUo+jSyv4Wu1vXGFObvLT4zwK2qKcBboYAAAz3SURBVOpWVU0B9wBXDtlHgXwTtw3YDaCq61R1t7t+AxAVkbqah/BQ9y6g+K6bYJvV5zHG1CYviX8OsKPg8U6Gt9pvBD4oIjtxWvvXjXCevwCeUtVhhW5E5BoR6RKRru7ubk+BV8qz138QAP8RxY3MaZo1F4AXj66rzzljzBRQrou7VwM/VdW5wOXAXSIycG4RORn4JvCJkQ5W1dtVtVNVOzs6autmJ39PLwBv/utvjLPn4U5c8gGe+P4XCP/6vycjLGOMmTAvd+7uAuYVPJ7rriv0UWAJgKquFpEIMBPYKyJzgV8CH1LVl0oPubL8sTgvzwqyoMhCaz5/gLM/87VJisoYYybOS4t/DbBQRBaISAhYCqwYss924BIAETkJiADdItIO/Aa4QVUfL1/YlROIJ0mErbKFMaZxjJv4VTUDXIszImcTzuidDSKyXESucHe7Hvi4iDwD3A18RFXVPe54YJmIPO3+zJqUVzJJgvEUqWiw2mEYY0zZiJOfa0dnZ6d2dXVVO4wBGxa0EGtr4i1P7612KMYYMyoRWauqnePvaXfujiuSSJOJWskFY0zjsMQ/jkgiS6apuHINxhhTyyzxjyOaypGzxG+MaSCW+MeQivcxI6ZoQW19Y4ypd5b4x7B62V86CzOtnr4xpnFY4h+DvvYaAOd+81+rHIkxxpSPJf6x9MfoDUO42UosG2MahyX+Mfj6Y8TC9icyxjQWy2pj8MfiJML+aodhjDFlZYl/DIF4kkTE6vQYYxqLJf4xBONJUlagzRjTYCzxjyEUT5Gycg3GmAZjiX8M4USGTNRm0DLGNBZL/KNI9PWw8NUkmaZItUMxxpiyssQ/iqduWwZAtqW5ypEYY0x5WeIfRXqfU3//xO/8rMqRGGNMeXlK/CKyREQ2i8gWEblhhO3HiMjDIrJORNaLyOUF277gHrdZRN5ezuAnkx5yJllvmXl0lSMxxpjyGnesooj4gVuAS4GdwBoRWaGqGwt2+zLOlIy3icgiYCUw311eCpwMHA38j4i8UVWz5X4hZdffD0C0yEnWjTGm1nlp8Z8FbFHVraqaAu4BrhyyjwL5gjZtwG53+UrgHlVNqurLwBb3fLWvr5++EPj8No7fGNNYvCT+OcCOgsc73XWFbgQ+KCI7cVr71xVxLCJyjYh0iUhXd3e3x9Anly8WIx6SaodhjDFlV66Lu1cDP1XVucDlwF0i4vncqnq7qnaqamdHR0eZQiqNPxYnZnV6jDENyEs/xi5gXsHjue66Qh8FlgCo6moRiQAzPR5bk/xWp8cY06C8tMrXAAtFZIGIhHAu1q4Yss924BIAETkJiADd7n5LRSQsIguAhcCT5Qp+MgVjSVKW+I0xDWjczKaqGRG5Frgf8AN3qOoGEVkOdKnqCuB64Ici8lmcC70fUVUFNojIvcBGIAN8phIjeg7seolnbr4OUqkJHR89/S2cvWE/a0+xET3GmMbjqUmrqitxLtoWrltWsLwROH+UY28Gbi4hxqI9e9tXWXzbb0s4w4MApK1cgzGmATXknbu5gwcA6Nm1lUwyXtTPqqvOHDjP9Ju/U62XYIwxk6YxO7H7+gBo7ZiDP1hkWeXWloHFSPvMckZljDE1oSFb/PT1EQtSfNIHaClI/G1HlDEoY4ypDQ2Z+H2xOP0TvPnK1zJtYLlp+qxyhWSMMTWjMRN//8QnSfe1tg4sN7VZV48xpvE0ZOIPxOIkIhNL/IFp7QPLE+oqMsaYGteYiT+RIjnBSdIDrW1ljsYYY2pLQyb+UiZJD1kZZmNMg2u4xH/wtVc4bcsh0hOcJD3cZonfGNPYGi7xP/+LHwCQmDOxETmz33Q+L84O8/sr3lTOsIwxpmY03A1cmd4eAI754rcmdPy0jrlM251gYTmDMsaYGtJwLf5snzNXrt18ZYwxI2u4xJ87dAiwm6+MMWY0DZf46Xfq9DRb4jfGmBE1XuLv6yMRgEDISiobY8xIGi7xSwl1eowxZirwlPhFZImIbBaRLSJywwjb/0FEnnZ/XhCRnoJt3xKRDSKySUS+KyKTmpX9/THi4Yb7PDPGmLIZdziniPiBW4BLgZ3AGhFZ4c66BYCqfrZg/+uAM9zl83Bm5jrN3fwYcDGwqkzxD+OPJ0hMsFyDMcZMBV6axmcBW1R1q6qmgHuAK8fY/2rgbndZcSZeDwFhIAjsmXi4Y4sd3Me5f9xF0iZJN8aYUXlJ/HOAHQWPd7rrhhGRY4EFwEMAqroaeBh41f25X1U3lRLwWLY99hsAeo+aPllPYYwxda/cneFLgftUNQsgIscDJwFzcT4s3ioiFw49SESuEZEuEenq7u6e8JMnD74OQPRvPj/hcxhjTKPzkvh3AfMKHs91141kKYPdPABXAX9U1T5V7QN+C5w79CBVvV1VO1W1s6Ojw1vkI0i7k6yH2qzFb4wxo/GS+NcAC0VkgYiEcJL7iqE7iciJwHRgdcHq7cDFIhIQkSDOhd1J6+rJ9B0EbJJ0Y4wZy7iJX1UzwLXA/ThJ+15V3SAiy0XkioJdlwL3qKoWrLsPeAl4FngGeEZVf1W26IfI9rqJf5rV6THGmNF4Gv6iqiuBlUPWLRvy+MYRjssCnyghvqLkDjkF2qxOjzHGjK6h7nRSt05P0/SJXycwxphG11CJn74+Un4IRVuqHYkxxtSshkr80tdvdXqMMWYcDZP4D+x6iYt//SyJoCV+Y4wZS8PUNvAFgqw+Zw6pC85jdrWDMcaYGtYwib/tyGM4d/XOaodhjDE1r2G6eowxxnhjid8YY6YYS/zGGDPFWOI3xpgpxhK/McZMMZb4jTFmirHEb4wxU4wlfmOMmWLk8PL51Sci3cArJZxiJrCvTOFUQr3FCxZzpVjMlVFvMY8W77Gq6qk0cc0l/lKJSJeqdlY7Dq/qLV6wmCvFYq6Meou5HPFaV48xxkwxlviNMWaKacTEf3u1AyhSvcULFnOlWMyVUW8xlxxvw/XxG2OMGVsjtviNMcaMwRK/McZMMQ2T+EVkiYhsFpEtInJDtePJE5E7RGSviDxXsG6GiDwgIi+6v6e760VEvuu+hvUicmaVYp4nIg+LyEYR2SAif1PrcYtIRESeFJFn3Ji/6q5fICJPuLH9m4iE3PVh9/EWd/v8SsfsxuEXkXUi8us6iXebiDwrIk+LSJe7rmbfF24c7SJyn4g8LyKbROTcWo5ZRE5w/775n14R+duyxqyqdf8D+IGXgOOAEPAMsKjacbmxXQScCTxXsO5bwA3u8g3AN93ly4HfAgKcAzxRpZhnA2e6y63AC8CiWo7bfe4WdzkIPOHGci+w1F3/z8Cn3OVPA//sLi8F/q1Kf+vPAf8K/Np9XOvxbgNmDllXs+8LN447gY+5yyGgvdZjLojdD7wGHFvOmKv2gsr8xzkXuL/g8ReAL1Q7roJ45g9J/JuB2e7ybGCzu/wD4OqR9qty/P8FXFovcQNNwFPA2Th3OAaGvk+A+4Fz3eWAu59UOM65wIPAW4Ffu/+4NRuv+9wjJf6afV8AbcDLQ/9WtRzzkDjfBjxe7pgbpatnDrCj4PFOd12tOlJVX3WXXwOOdJdr7nW4XQpn4LSgazput9vkaWAv8ADOt8AeVc2MENdAzO72g8ARlY2YfwT+Dsi5j4+gtuMFUOB3IrJWRK5x19Xy+2IB0A38xO1S+5GINFPbMRdaCtztLpct5kZJ/HVLnY/omhxTKyItwC+Av1XV3sJttRi3qmZV9XSclvRZwIlVDmlUIvIOYK+qrq12LEW6QFXPBC4DPiMiFxVurMH3RQCnq/U2VT0D6MfpJhlQgzED4F7fuQL496HbSo25URL/LmBeweO57rpatUdEZgO4v/e662vmdYhIECfp/4uq/oe7uubjBlDVHuBhnK6SdhEJjBDXQMzu9jbg9QqGeT5whYhsA+7B6e75pxqOFwBV3eX+3gv8EucDtpbfFzuBnar6hPv4PpwPglqOOe8y4ClV3eM+LlvMjZL41wAL3RERIZyvRyuqHNNYVgAfdpc/jNOHnl//Ifcq/TnAwYKvdhUjIgL8GNikqt8p2FSzcYtIh4i0u8tRnGsSm3A+AN49Ssz51/Ju4CG3FVURqvoFVZ2rqvNx3q8PqeoHajVeABFpFpHW/DJO//Nz1PD7QlVfA3aIyAnuqkuAjbUcc4GrGezmgXLGXK2LFpNwEeRynNEnLwFfqnY8BXHdDbwKpHFaHx/F6Zt9EHgR+B9ghruvALe4r+FZoLNKMV+A8zVyPfC0+3N5LccNnAasc2N+Dljmrj8OeBLYgvOVOeyuj7iPt7jbj6vie2Qxg6N6ajZeN7Zn3J8N+f+zWn5fuHGcDnS5743/BKbXQczNON/o2grWlS1mK9lgjDFTTKN09RhjjPHIEr8xxkwxlviNMWaKscRvjDFTjCV+Y4yZYizxG2PMFGOJ3xhjppj/D/w/VEPC/hH5AAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "from matplotlib import pyplot as plt\n",
    "%pylab inline\n",
    "\n",
    "start = 0\n",
    "end = result2.shape[2]\n",
    "\n",
    "x = range(result2.shape[2])[start:end]\n",
    "plt.plot(x, p[start:end], color='green', linestyle='solid')\n",
    "plt.plot(x, myelu(c[start:end],-233), color='red', linestyle='solid')\n",
    "# plt.plot(x, np.array(p)-np.array(c), color='blue', linestyle='solid')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXYAAAEDCAYAAAAhsS8XAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAgAElEQVR4nO3de5AdZZkG8OedzCSEyybGDIgGmISbiRduA4hQYRdYNroYhNKVlIqKEEtXNCWWwKprLaWl7JYXUERSyrq43ETBKMICGtRlFXBCEsKdBCIQgUQxgCBkZvLuH92fp+fMuXZ/3f29fZ5f1alz//qbM32eec/bPX1EVUFERNXRV/YEiIjILwY7EVHFMNiJiCqGwU5EVDEMdiKiimGwExFVTGnBLiKXishmEbnHw1h/JyJrEqeXROTtPuZJRGSNlLUfu4gsBPBnAJep6us9jjsLwHoAc1T1RV/jEhFZUVrFrqq/AvBM8jYR2VtE/kdEVonI/4rIa1MM/Q4ANzLUiahXhdZjXw7gTFU9BMAnAXwzxRinALjS66yIiAzpL3sCjojsDODNAK4REXfztPi+kwGc1+Bpm1T1HxJj7A7gDQBuyne2REThCibYEX162KqqB9bfoarXAri2gzH+CcB1qjrqe3JERFYE04pR1ecAPCoi7wQAiRzQ5TBLwDYMEfW4Mnd3vBLAbwDsLyJPiMgHAbwbwAdFZC2AewGc2MV4QwD2APBL/7MlIrKjtN0diYgoH8G0YoiIyI9SNp7Onj1bh4aGylg0EZFZq1at+oOqDrZ7XCnBPjQ0hJGRkTIWTURkloj8rpPHsRVDRFQxDHYioophsBMRVQyDnYioYhjsREQVw2AnIqoYBjsRUcWEdHRHKthttwE33wwcdhgwMgJs355+rN12Az7yEaB2xOX8PfsscNFFwOgo8IEPAHvumX3M228HbrgBOOkkYO1aYOZMYMYM4NZba4856ijg+OOjy/fcA3z/+9mXW1WzZwNnntl4vfjNb4Abb0w37sknAwdOOg5stC5ceGG0bvi0ww7A/PnA6tWN71+wADjlFL/LzERVCz8dcsghSuVbuFAVqJ1E0p3c8x9/vNj5X3VVbdnnnednzOOPj8ZbvLg29vBw7fUBVOfPrz3+/e/P9tpV+eRev4cfbv1apxn3Xe9qPOadd2Zfn5v9HM3GBVSnTfOz/rUDYEQ7yFi2YnrYyy/XLg8MRBV7mtOll0ZjjI0VO//k8nwt270m27ZNvO2kk6Kf9d3vnnzfvvumf+2qfLryyta/m9FRYOHC7sd93etajwlEn0R9/RwPPVQbf/Hiyfd/9rMT14kQMNh7WNFBnKcsbaQk95okD3o6Ngb0x03L/v7Jf1D62dBsqC9Ol2a/m+3ba4/pdtxWYyaXXYT+/mh98bUO+sBg72HJgMrSG3fPLfoI0MnlMdjDU5VgT743Gr1P3O8/pEKJwd7DfK+IVQr25HgM9nSqEuztMNgpKL4r9jKxYg9PVYKdFTuZwlbMZI2Cfds2BnsaDPbyMNh7WEgrYhpFtWJeeonBnkZVgr0dBjsFxXrFnpRnxc5gT6cqwc6KnUyxHuxFtWJefpnBngaDvTwmg/0LXwCOOw544YV0z7/sMuDII4HfdfQlU9UV0oqYVZ7BDkwM9vHx2v0M9ubaBfv4uP9gHx+fuOwihBjsJlfJz3wmOn/ssej4Dd36/OeBhx8G1q0D9trL79wsYcU+WSfBDkQB4qp3BntjrNjLY7Jid9IGifvll9kTDoH792uAwe6416R+vPpgd29iBntzDPbyePvxRWSKiKwWket9jUn5CmlFzMp9BM+q04rd/QEYHWWwN1OVYG+nfp0Igc8f/+MA7vc4XltZK8Rer9jZipms02Bnxd5eVYK9Zyt2EZkD4B8BfNvHeJ1isKfnjkznU5WCvX68gYGJ58lgd7fRRFUJ9nbq14kQ+PrxvwbgUwCavr1EZKmIjIjIyJYtWzwtltKqb11YPqRAqzd6t1ix+1OVYO/Jil1ETgCwWVVXtXqcqi5X1WFVHR4cHMy62HjMcp9vWf1KaLkVM2WKn2BPfophsGfnwrXZ9o8swd5qzOSyfejJYAdwJIDFIrIRwFUAjhGR//Ywblt5BHuaA+aPjwMvvuhvA14RQloJ0/Id7MnfH/eKya4qFXs7lQx2VT1XVeeo6hCAUwCsVNX3ZJ5ZCVauBKZNA84/v7vnHX44sNNO0T89WVGFit3x1YpJvias2LOrSrD3asVeGt8V+yOPROe3397dOO6rszZsyDafIlUh2H1X7Ax2vxjs5fG6SqrqLwD8wueYrZfn9/nuF9PtStFsg1vIQloJ03Kvdx4VO1sx2VUl2NsJMdhNV+y+9XKwW6zYHVbsYapKsFus2E0He2gVuyVVCPayWzGqDPZW8gr2Vr9vBnvEXLAnf6EhBPv27bVxLFfslpW18dQtk8HeWFUq9nYY7B7k+eKlCfZWYRAyVuyTdRvs7vEM9saqEuys2AvgM0h9VOwh/TK7UX/AIgb7xNek3cbT0dHa4xnsjfVasId0EDBzq6TPIG0W7N2EnNWK/a67yp6BP75aMWvW1C63q9jvvBN47rmJt9FEVQn2dtzvf9064Omngd12K27ZzZhbJfMM0mYHgOp0PlY88wzwgQ9MvK3XK/bnnwfe9a7JYzuveEV0PmtWdH7uuZPvo4mqEuztKvadd47C/cILgQceAG66yd+y0+rpYG9WsacJ9oEBOxX7889H52eeCfz618Cqlkf56ZzlYHdfs3j66cD990eVFwB88pPAe94DvPGN0fX584G77waefTa6PjAADA9nW3ZVVSXY29llF+C++6L1xK0XZTMd7L41+/acViwGu5vzoYfW/su214/u6F6Tww8HHnyw9rucPx844ICJj33DG7Itq1dUJdjbVewAsO++wOAg8NRT/pabBTeeNhg7TbBb6rM2mnOvt2LqXxMrf6RD1kvBDtS+AzcEDPYGY3cTEq7Kt1ix9/eXX21nkVewi9TGs/z6lK1dsI+P+w92d4TOIlsxDoM9gyL2Y++VVkwy2C1W7I7PVox7TdzPwmBPr1Wwq0YnVuz5MBfsyX1FQ6jYk8FuBVsxk7EV41+7YE8+pttxGeytmQv20FoxVanYLWIrJmytgj1LAIe2V4zDYM8g1FZMf7/tYLdYsTt5BDtbMdmVGew+f2+s2AsQcsVuBVsxk7EV49+UKdF5q2B3j+lGu2BPM2YrDPYC/OIXtcuhBbuVMKhaKyaPjadsxWRXVsVeRhsGYLBncttt+Y3NVkw6bMVQI1UJdlbsBSjieOxVb8U0OiqhxWBPtmLc/stpsRXjXy8GeyhHeDQX7EUc3ZGtGFu4H3uYqhLsnWLFnkGoR3fkIQW48ZQmqkqwsxVTgJD3irESBsk5W65IuR972PIMdqDx+63Min1gIFq+j+8GyMpksOf1i+u1oztWZeMpWzFhyjvYm41bZsUOZN/e44PJYPf1cZlHd6zdZjHY2YoJm1svfAd7u/3jyw72ENoxJoPd7YESUrBbr9gtYismfM0+TVmq2DvFYM8gGew+/f73wOrV0eVeDHaLFbvDVky4qhDsrNgLMDqaTytm7draZbZiusNWDDXDYC+HuWAfGwOmTo0u+wx298t49av5RRtWsBUTvioEe6cY7Bnk1Ypxv4ypU7vbqs1WDFsx1FwVgp0VewHy2ismGexVP6QAWzGTsRWTDwZ7OUwGex57xfRqsFuuSH0Ge/L4OWzF+FOFYO8Ugz2DIloxWTaeWqj03JynTGErxmErJh99fY1bmz6Cvdm4rNg9BLuI7CEit4rIfSJyr4h83MfEmmErJrvR0YmhDtgMdrZiwtfsj64LZd8V+/h4+cEewhEefeykNwbgLFW9S0R2AbBKRG5R1fs8jD15YR4rdp/BngyEvKq80dGJ3zyTZhfL0VHg5Zdrz61CRdrXB2zblm0M93z3B48Vux99fbV1Lumll2r3pxkTAP7yl8nj5nnIkXbce+rFF6N5DQyUN5fMi1XVJ1X1rvjy8wDuB/CarOM247PHXj8ukC7Y66vfPKxcCUyfDuywQ3TaZRfgwQe7G+PXvwZ23BH48pejMZIsV+wiwJ//HJ2n/SKWz3++NlZybMpm6lRg+fLaeutOw8PR/WmKNLe787x5k8f9wQ/8f3rutGJ376kjjoguH32033l0w+u/1YjIEICDANzhc9ykEFsxyY2QeQXChg3Rx8xzzgH+9CfgkkuAxx4D9t+/8zEeeSSa71ln1VY6yxWpe62XLAEuuii6fPXVwFFHpRvv4IOjc2489ec736n9R3e96dOB447rfsy3vx145pnJ1brz5jd3P6YPCxcCF1wAvPACsGJF94WXT96CXUR2BvBDAMtU9bkG9y8FsBQA9txzz9TLyasV4/pioQa7+8OzbBmwcWMU7N1upHGP/+hHgaGh6HIVNp7OnZvt+W7eb3tbdO5r2wMBixZFJ59mzgQ+8Qm/Y7bS6fowfTrwsY9Fl598EnjooXzn1YqXDpCIDCAK9ctV9dpGj1HV5ao6rKrDg4ODqZazfXv0JsyzFTNtWrpgz1uyl59263urwx9YDPbkxtMs3IY8S4eFoOKk+UNf9pdu+NgrRgB8B8D9qvqV7FNqzveeC41aMWmDvaiK3XewW65IfQV7/evCip2yMh/sAI4E8F4Ax4jImvj0Vg/jTpLnroWh99jzDnaLFbuTdc8DBjt1ykrFnvnDp6reBqCQ1T/534HRsrONV1+xi0RjsxXTnbJbMb6Dnaie2wXWSrCb+s/TZFUN+A/2/v7u/4uxKhW7Re6NxoqdQtPfH62fZX3/qclgz6sVkyXYnbyDva+PrZh6DHbKW7fvk7IPL2Ay2PNqxaQJdvfFH3kHQPKTAVsxteXlUbET1WOw5+jOO6PzvI7uGHorxq0sWYM9uReJ5Yq0UbCnef1ZsZNvDPYu/OhH0fmuu/of20IrxkewNzv4l8WK3WErhvLGij1HX/wi8PDDwAknRNdDqdgHBvIPgOR3vaY9ilxyjHo+gr1ovlox9XtbEdVLG+xlHenRVLC/+tXAPvv4C5JebMXUh5fPUK5Kj50VO2XFij2FPELUVysmL8lj5LjzNMFev0cRWzGT97ZisFO9bt8nad+jvpgMdieUVozlit0yX8e+514x5Bsr9hTyaMW4/nOzr/Jqpoxg7+uLluezFWO1Ys8j2FmxUz1uPC1A3q0Y1c7HLrIVk1xOmn9ZbjVXi8Hua3ms2KkdBnuBfLdikl9l1W2wF1mxA/6C3XJFmlcrhhU7ZVV2sJusUXy/2cbHgeuvBw49tBbsy5a13yg3fTqwZQuw5572g91ixe4Lg53asVaxmwx2x1fF/sAD0Xl/P3DAAcCsWcBll7V+7vh49D2bAHD44dnm0Qm2YibjxlMqCoO9AL6CxD3ffUP92WcDixcDf/xj++c+9FDt+0bZiikHWzEUqrKD3WSP3febLU3FVh+yjtVgt1ix+8Jgp3asVewmg93xVbH7CPaiju6YXCZbMWzFUDHcus1gz5HvVozPYLdasVvEVgyFisGeAlsxbMX4xGCndtiKKVCIFXte6o/M2N/Pozs2qtjTzIVHd6RO8eiOOfJ9SAG2YvyoSo+dFTtlVXbFbrJG8R2iPlsxebj4YmDNGmDu3NptAwPArbcChx3W+Tj33gssXDjxtl5vxXz1q8AFF0SXGezUTLcbT93RHc8+G9i6FTj99Hzm1YzJYHd8tWLSfBRPPjb5RRt5hNsPfxidv/e9tduWLgVWrOhunKOPBk491d+8yuajYr/mmugfzc44Axgc9DMvonnzovfrihXRN78x2DvQa62YsbEolE86qXbbhz4UnbKyXrFnXRfGxqJPPcuXNx6TFTsB3b9Ppk6N/nv9TW8qpx1jusdeZismeRyZvFsxRRxB0mKw+1he1Y5RT/nothXjpNkW5oPJYHd87xVT/+1CnSqiYs8rfCxXpI1aMd2+/u02KFt+fah8DPYuhNCKSapCsFus2JPLTovBTp1I+z5hsHchhFZMElsx0TlbMVRVbMUUqMx/UEqqQsVukY+9YlixU54Y7F0I4ZACSXkfUoCtmPww2KkTbMUUKG2QuOflUbHnwUorpmh5bTwlaobBnqOsFWKewW61YvchhEMKbN/e3Ris2ClPDPYu9ForptXBu7KqWium22Bv9Noy2KmZNBV7GQcC8xLsIrJIRB4UkfUico6PMTsRYsWeB7ZiGsurYidqpmdaMSIyBcBFAN4CYAGAJSKyIOu4rZfpZ5xksItM/G/SbrAVE2Erhmgis8EO4DAA61X1EVXdBuAqACd6GLcpXz12J2twFrEfe9r/im2n11sxjV5bBjvVS7sf+8CA3WB/DYDHE9efiG+bQESWisiIiIxs2bLFw2L9tWKy9rAtV+yWZa3YVfnaUr4sV+wdUdXlqjqsqsODGY+PmkcrpleD3XLFnjXY3WPZiqF2enE/9k0A9khcnxPflpvQWjF5tUkcBnvnugn2ZhvNGexUrxcPKfBbAPuKyFwRmQrgFAA/9jBuWz73iskSznlW7Nu3Rye2CybLWrFn3RuKqJ2ygj3zKq2qYyLyUQA3AZgC4FJVvTfzzFrw3Yq5445sY+YZ7OPjtWXkwXrFnkews2Kner3YioGq3qCq+6nq3qr6BR9jtuKzFfP888Dq1cCzz3Y/zrHHRuevfGW6eXSiqKrSYrA3Wh4rdspDllaM+9RdJJP/eer4aMX85S/R5c9+tvtxfvIT4NFHgQUL8gu3vMPHckWaVyuGFTv54tYt98m7KCaD3eebzb25Z8/u/rnTpwNDQxNvsxrsFiv25LIdBjvlIUsrBii+HWMy2B0fFbuv4MwrACy1YorGVgwVjcGeI58bT30Hu9WK3Qdr+7GzYqe8Mdi74HPjqe/g9B1u7shwbMV0pptgb/baMtipmbQVe9FHeDQZ7A5bMf5YbcXUL7ubjVRsxVC32IrJEVsx/rAVw4qd8lNWsJusVUJuxfi0fj1w/vnRZR7dsTMPPACcdVZnj3366eicR3ekdrIc3REAzjsPmDEjunzGGcBrX+tvbo0EGGed89GK8dXDziPcvvtd4NJLgcFBYL/9/I1bFcmK/cwzga9/HfjTn4DlyzsfY7fdgH32yWd+RPPnR7tSX3117bZFixjsDfVKK2bbtmhf+c2b/Y1Zz3LFngz2Cy+MTj6wYqd6ad8nhx4KeDpKeVdM99ir3oop8ivxLAZ7XhjsVC9tK6YsJoPd8blXTNYedh7hxi+BaK3RxlMiMhrsvdKKYcXe+bLzGpN/OAjw8z4pkulgZyvGH6v7sRMVicFegBD/Qclqxe5DCPux+8CKnawzGewhtmKSY/rCVkzny85rTAY7JVlZHwJsQLQXYismj1+4tVbMT34CXHHF5N/LokXA5z4X/bv/kiXA449PHuPEE4FzzokuX3FFtE96K9OmAc89l37ORGlYCXaTFbsvbMX4XVFvvhlYtQr4m7+pnTZuBC6/PLr/mWeAa64Btm6d+JgNG4Arr6yNc911wLp1Ex+TPPX3A7/8ZfTNV6zYiSZjxd7jG099tmIAYNddgZtuql0/9VTgttuiy+61XrYM+NCHao955zuB++6rXR8bA/bee+I4SY8+Csybl33ezTDYqRkr64Ppip0bT/3xFez1801+mW+z17r+C3/b/dx9ptdasozBnqMQN57mEeyjo7ZaMUDxwc6KnWgy08HOVkx2vlsxDHaqIh5SoEBVP7qjxUMKsBVDVD6Tb5FeacWMjeV3HHaHFftkrNipHg8pUIA8WjF5B2gabMU0lnfFzmCnemzFFIh7xYSnChU7kXUmg91nK+aFF6LLU6ZkG8tqsFuv2NmKoSKwFVMAn62YL31p4pghqUqwq0ZfMs1WDFlnZX0wGeyOj1YMABxxRPa5WK3YfWsU2kC091GzPZD6+2v3uceyFUOUnslg99mKEQGOO87PeG5MX6pSsQPRz9KqYndVvXssWzEUIivrg+lgz1qxb98eXfYRnjy6Y6R+7yJ3PRnsrR7jzlvtpcT92KksDHYDfP1zEmC3FVPEIQWA9hW7e4w7Z8VOlF6mYBeR/xCRB0TkbhG5TkRm+ppY6+VG51kr9pAPJwD0VivGPcadM9gpRFbWh6wV+y0AXq+qbwTwEIBzs0+pc1mDnRV7jdVgJypSTwS7qt6sqm5HtdsBzMk+pfZ8vbgMdrZiGmHFTtb5rH1OA3BjsztFZKmIjIjIyJYtWzItiK0Yfyy2YkTy/YcRBjvVq9whBUTkZyJyT4PTiYnHfBrAGIDLm42jqstVdVhVhwcHB71Mnq2Y8BQR7ADbMUSttI0NVW25l7eIvB/ACQCOVS3me+p9/dXcti06DzXYi/yiDUsVOxAF+/g4K3YqhrVDCmSKDRFZBOBTAI5W1Rf9TKmT5UbnvloxIR7ZUTUKrl4L9k5/blexM9ipSFbWh6wfaL8BYBcAt4jIGhH5loc5dazKrZjx8eg8xD86rWQNdvdzsxVDlF6mSFPVfXxNpBu9sFdMURt2Q6vYO/25WbFTGaysDybrnl7YK6boYPc1RtHBngcGOzVjZX0wGexO1uqYFbt/aY/u2O4x9fKs2ImsMx3sWfkMdsdasFuv2NmKoSJZWR+M1YM1IulCtNH3nYZ4dEdLFXsnR3e85BJg06YokOvbKO4x3/gGMGtW43HqceMplYHBbgBbMf5X1AULJl7fay/gVa8CfvrT6Pqhh05+zty5wK67AitWRNdnzADmz2+9HFbsRM2ZDXYfFXserRhfLAV7cowTT5x43+67A08+2fr5Q0PA0093t0wGO5XByvpg9gNtqK0YaxW7D2Ws7GzFUBkY7AawFWNnRa3Hip2oObPBHlrF7huDvTUGOxWpckd3DFlIPXarFbtVbMUQNWf27eHjL2enxyXphNVgt1KB1GPFTkWydnRH08GetWJ3QjzQFoO9NQY7lcHK+mA22AF/wR5ixR7yrpghYCuGqDmzbw+ffzl5SAF7WLFTGaysD6aD3VfFPmWKn/n4xGBvjcFOZbCyPpgNdsBfsL/qVdnnktfG0xD7/yFgK4aoObNvD19/OU87ze9fYbZiisGKncpgZX0wHew+KnZfwclWTLH4RRtUBivrg9lg98V3sFur2K3iF20QNWc22EOr2H1jxd4aWzFUBivrA4OdFbtJ3HhKZWCwG9HrwW5lRa3Hip2oObPBHlrF7huDvTUGO5XByvpgNtiBsILdasVuFVsxRM2ZfXv4+svZ68FupQKpx4qdymBlfTAd7D4q9lD/s5PB3hqDncpgZX0wG+wAWzG9jK0YoubMvj1Ca8U41oLdSgVSjxU7lcHK+mA62EOs2H1hsLfGYKcyWFkfzAY7EGaw+/6iDbYcGuPrQtSc2bdHL7Ri+vvzrxCsVCD13DH0WbFTkaysD6aDPcSK3ZexsWL22LGyotZjK4bKYGV98BLsInKWiKiIzPYxXpFCbcW4ij1vM2dG53PmZB/r2GOzj9GpWbOiczd/n9yYfX123siUr6OOis7zWN/ykDk6RGQPAMcDeCz7dLpZblgVu29FBfuSJcCBBwL7759tnK1bgenT/cypExdfDHzsY8D8+f7HPvlkYN266I8He/kEANdeCzzxBLDffmXPpDM+ouOrAD4FYIWHsToWWrBbrdj7+oDXvS77ODNmZB+jGzvuCBxySD5jiwCvf30+Y5NNO+5oJ9SBjK0YETkRwCZVXdvBY5eKyIiIjGzZsiXLYr3q9WAnouppGx0i8jMAjb7u+dMA/gVRG6YtVV0OYDkADA8PZ46/0Cp23xjsRJRW2+hQ1eMa3S4ibwAwF8BaicrVOQDuEpHDVPUpr7NsuPywgp0VOxGFInV0qOo6ALu66yKyEcCwqv7Bw7wK42uXQgY7EYXC7Db/0Cp23xjsRJSWt+hQ1SFfY3W+zOzPYSuGiKrGdMXuQ+iHFCAi6pbZ6BABfvUr4Iwzunveiy9OvB7yIQUY7ESUhtnoOOYYYOVK4IYbun/u0BAwbx6waVN02Qe2YogoFGaj43vfK3sGjTHYiahsZnvsofHdihkdZbATUToMdk/YiiGiUDDYA8VgJ6K0GOye5FGxF/FFG0RUPQx2T9iKIaJQMNgDxWAnorQYHZ64iv3ss4EvfjH7eBs2AAcdlH0cIuo9DHZPhoaAD38Y8PUdIgsWAKed5mcsIuotDHZP+vuBb36z7FkQEbHHTkRUOQx2IqKKYbATEVUMg52IqGIY7EREFcNgJyKqGAY7EVHFMNiJiCpG1NdRq7pZqMgWAL9L+fTZAP7gcTpF4JyLYW3O1uYLcM5FaTbnvVR1sN2TSwn2LERkRFWHy55HNzjnYlibs7X5ApxzUbLOma0YIqKKYbATEVWMxWBfXvYEUuCci2FtztbmC3DORck0Z3M9diIias1ixU5ERC0w2ImIKsZUsIvIIhF5UETWi8g5Zc/HEZFLRWSziNyTuG2WiNwiIg/H56+IbxcRuTD+Ge4WkYNLmO8eInKriNwnIveKyMcNzHkHEblTRNbGc/63+Pa5InJHPLerRWRqfPu0+Pr6+P6houecmPsUEVktItdbmLOIbBSRdSKyRkRG4ttCXjdmisgPROQBEblfRI4IfL77x6+tOz0nIsu8zllVTZwATAGwAcA8AFMBrAWwoOx5xXNbCOBgAPckbvt3AOfEl88BcH58+a0AbgQgAN4E4I4S5rs7gIPjy7sAeAjAgsDnLAB2ji8PALgjnsv3AZwS3/4tAB+OL38EwLfiy6cAuLrE9eMTAK4AcH18Peg5A9gIYHbdbSGvG/8F4PT48lQAM0Oeb93cpwB4CsBePudc2g+U4gU4AsBNievnAji37Hkl5jNUF+wPAtg9vrw7gAfjy5cAWNLocSXOfQWAv7cyZwA7ArgLwOGI/juvv34dAXATgCPiy/3x46SEuc4B8HMAxwC4Pn5zhj7nRsEe5LoBYAaAR+tfp1Dn22D+xwP4P99zttSKeQ2AxxPXn4hvC9VuqvpkfPkpALvFl4P6OeKP+wchqoCDnnPc0lgDYDOAWxB9gtuqqmMN5vXXOcf3PwvglcXOGADwNQCfArA9vv5KhD9nBXCziKwSkaXxbaGuG3MBbAHwn9bXrN8AAAJGSURBVHG769sishPCnW+9UwBcGV/2NmdLwW6WRn9mg9uvVER2BvBDAMtU9bnkfSHOWVXHVfVARFXwYQBeW/KUWhKREwBsVtVVZc+lS0ep6sEA3gLgn0VkYfLOwNaNfkRt0ItV9SAALyBqY/xVYPP9q3jbymIA19Tfl3XOloJ9E4A9EtfnxLeF6mkR2R0A4vPN8e1B/BwiMoAo1C9X1Wvjm4Oes6OqWwHciqiNMVNE+hvM669zju+fAeCPBU/1SACLRWQjgKsQtWMuQNhzhqpuis83A7gO0R/RUNeNJwA8oap3xNd/gCjoQ51v0lsA3KWqT8fXvc3ZUrD/FsC+8R4FUxF9hPlxyXNq5ccA3hdffh+iPra7/dR4S/ebADyb+PhVCBERAN8BcL+qfiVxV8hzHhSRmfHl6Yi2CdyPKODf0WTO7md5B4CVcRVUGFU9V1XnqOoQovV1paq+GwHPWUR2EpFd3GVEPeB7EOi6oapPAXhcRPaPbzoWwH2hzrfOEtTaMIDPOZe10SDlhoa3ItqDYwOAT5c9n8S8rgTwJIBRRBXEBxH1Rn8O4GEAPwMwK36sALgo/hnWARguYb5HIfqYdzeANfHprYHP+Y0AVsdzvgfAv8a3zwNwJ4D1iD7STotv3yG+vj6+f17J68jforZXTLBzjue2Nj7d695nga8bBwIYideNHwF4RcjzjeexE6JPYzMSt3mbMw8pQERUMZZaMURE1AEGOxFRxTDYiYgqhsFORFQxDHYioophsBMRVQyDnYioYv4f7jBJ9L9XDKcAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "X = x[start:end]\n",
    "Y = np.array(p)-np.array(c)\n",
    "Y = Y[start:end]\n",
    "\n",
    "plt.plot(X, Y, color='blue', linestyle='solid')\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
